### ISSUE TITLE
Multiple registered type implementations

### ISSUE THREAD

**Issue by grahamehorner** [MV10/Azure.Functions.Dependency.Injection#3]
Add support for injection of multiple type implementations

**Comment by grahamehorner** [comment]
[Inject("FunctionName")]
ISomeInterfaceType[] instances

or

[Inject("FunctionName")]
ICollection<ISomeInterfaceType> instances

etc..

**Comment by MV10** [comment]
Thanks, it was "multiple" that was throwing me off! Merged.
